# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  namespace: default
  labels:
    app: symfony
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony
        image: 954976299895.dkr.ecr.us-east-1.amazonaws.com/webdev77:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: symfony-config
        - secretRef:
            name: symfony-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10