apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony
        image: 954976299895.dkr.ecr.us-east-1.amazonaws.com/webdev77:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: symfony-config
        - secretRef:
            name: symfony-secrets
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        startupProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
      imagePullSecrets:
      - name: ecr-credentials